### ISSUE TITLE
关于PaaS平台双活方案

### ISSUE THREAD

**Issue by jinxin-fu** [TencentBlueKing/blueking-paas#1344]
整个bk集群，是否支持双集群双活的部署架构

**Comment by piglei** [comment]
你好，可否补充一下对双活的具体要求？比如：

- 需求场景：在什么场景下需要这种部署策略？
- 所涉及的产品：蓝鲸开发者中心、所有蓝鲸 SaaS、或是含其他任何蓝鲸平台下的服务？
- 已有的实践：如果方便可以分享目前你们已经尝试过的部署实践。

感谢。

**Comment by jinxin-fu** [comment]
> 你好，可否补充一下对双活的具体要求？比如：
> 
> * 需求场景：贵公司在什么场景下需要双活部署策略。
> * 所涉及的产品范围：所有蓝鲸 SaaS、蓝鲸 PaaS 开发者中心、还是包含其他所有蓝鲸平台服务？
> * 已有的实践：如果方便，可以分享以下你们已尝试过的部署实践。
> 
> 感谢。

目前是单集群部署，目前在考虑同城双活方案，灾备，部署范围是包含其他所有蓝鲸平台服务，目的是做高可用，确保单边故障的情况下保证服务可用

**Comment by HeraZhang** [comment]
更多蓝鲸在企业内的特定场景需求，欢迎联系合作方了解 https://bk.tencent.com/cooperation_partner/
