### ISSUE TITLE
【优化】部署分支接口拉取时间过长，甚至出现超时

### ISSUE THREAD

**Issue by caohua** [TencentBlueKing/blueking-paas#249]
描述：
<img width="936" alt="企业微信20230309-111731@2x" src="https://user-images.githubusercontent.com/5043740/223908809-cc2dbe42-7fb2-46df-a57c-deff1eea3b08.png">
部署的代码分支接口有性能问题，感知就是代码仓库提交越多（用得越久），拉分支数据就很慢，甚至有个应用一直超时，部署不了

如何复现：
1、选取不同时间段的代码仓库，刚刚新建的、长期频繁迭代的，分支接口的性能有比较大的差距
2、原来超时的仓库，把分支有12个删除了绝大部分，只保留2个分支，最终可以拉取，但时间比较长
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/5043740/223909537-345dcff0-6ee9-406d-85d1-0a5624adef8d.png">

**Comment by jiayuan929** [comment]
已经在这个 pr 中优化了代码分支的拉取速度：
https://github.com/TencentBlueKing/blueking-paas/pull/789
