### ISSUE TITLE
请问APIGateway相关源码在哪里

### ISSUE THREAD

**Issue by goluckycoding** [TencentBlueKing/blueking-paas#396]
在7.0版本中用的ebs发现是legacy-bk-paas老版本的，有些接口对不上，比如authorization/resource_creator_action是在iam-saas中，不在iam中，请问新版本esb也就是apigateway是在哪里呢

**Comment by narasux** [comment]
https://github.com/TencentBlueKing/blueking-apigateway
https://github.com/TencentBlueKing/blueking-apigateway-operator
https://github.com/TencentBlueKing/blueking-apigateway-apisix

新版 APIGateway 已在 Github 上开源，欢迎移步到对应项目查看
