### ISSUE TITLE
超长自定义进程命令在进程管理页面的显示溢出问题

### ISSUE THREAD

**Issue by linxiaowu1992** [TencentBlueKing/blueking-paas#694]
## 问题描述
在app_desc.yaml文件中，自定义进程命令：
command: python manage.py celery worker -Q pipeline_additional_task,pipeline_additional_task_priority,task_common_${BKFLOW_MODULE_CODE},node_auto_retry_${BKFLOW_MODULE_CODE},timeout_node_execute_${BKFLOW_MODULE_CODE},timeout_node_record_${BKFLOW_MODULE_CODE} -n common_worker@%h -P threads -c 10 -l info
命令比较长，在进程管理页面显示溢出：
![image](https://github.com/TencentBlueKing/blueking-paas/assets/29301212/92fadfb4-c9ff-4271-9847-ac7d8ad136db)

**Comment by jiayuan929** [comment]
已修复
<img width="1013" alt="image" src="https://github.com/TencentBlueKing/blueking-paas/assets/22972765/ef34b854-30b1-45bd-b3f2-4832f706c4ac">
